Dockerfile
config/environments/development.rb
docker-compose.production.yml

- uncomment command in docker file
- add line from @freeatnet  to production YAML
- fix port number in `development.rb`

fix production setup

---

app/controllers/mangler.rb
app/controllers/offers_controller.rb
app/models/offer.rb

add offer link to /offers routes

---

dev-run-clean.sh
prod-run-clean.sh

add shell scripts from TAPP

---

db/migrate/20170828170241_drop_campus.rb
db/schema.rb

create migration to drop campus model

---

.gitignore
dev.env.default
docker-compose.yml
prod.env.default

remove unused environmental variables

---

app/services/contract_generator.rb
app/services/offer_importer.rb
app/services/template_parser.rb
app/services/templates/office_form.html.erb

Port of @michellemtchai's CP PR #29: https://github.com/uoft-tapp/cp/pull/29
- update contract format as described in meeting with Lisa and Marina
- mapped program_id to HR position number:
- UG = 14935
- SGS I = 14936
- SGS II = 14937
- fix issue with file offer import

update pdf contract format

---

app/controllers/offers_controller.rb
db/schema.rb
spec/controllers/offers_controller_spec.rb

allow withdrawn status to overwrite accepted/rejected

---

app/controllers/positions_controller.rb
spec/controllers/positions_controller_spec.rb

make start_date and end_date in Position model editable

---

prod.env.default

add hr-admin mail info to prod.env.default

---

README.md

update README with email task command

---

backup.sh

backup script for cron.

---

app/controllers/app_controller.rb
app/controllers/authorizer.rb

protect /roles route

---

app/controllers/offers_controller.rb

add protect from forgery to offers controller

---

app/controllers/app_controller.rb
app/views/app/decision.html.erb

set up log out button on decision page

---

app/controllers/import_controller.rb
app/javascript/cp/fetch.js
app/javascript/tapp/fetch.js

Front-end follow up to #42 and #3 
Also fixed a typo in import controller

Import error messages

---

app/assets/stylesheets/cp.css
app/javascript/cp/components/navbar.js
app/javascript/cp/fetch.js
app/javascript/tapp/components/navbar.js
app/javascript/tapp/fetch.js

added front-end logout support

---

app/javascript/tapp/components/abc.js

Made the course panel key change when the course changed, to force it to be re-rendered
(Based on [this](https://stackoverflow.com/a/35004739) Stack Overflow response)

Fix bug #29 (and possibly #45)

---

Dockerfile
app/controllers/app_controller.rb
app/controllers/authorizer.rb

- fix session ended for Shibboleth

[WIP][hotfix] test session ended

---

app/controllers/export_controller.rb
app/services/csv_generator.rb
config/routes.rb

- as described above
- `GET /export/cp-offers/:session_id`

finish export route for cp offers

---

app/javascript/cp/appState.js
app/javascript/cp/components/controlPanel.js
app/javascript/cp/fetch.js

Note that I have allowed the hr assistant to do this as well - maybe it should be restricted to admins?
@reidka @jmzaleski thoughts?

added ability to export offers from cp

---

app/controllers/offers_controller.rb
config/routes.rb

- `POST /offers/can-clear-hris-status`
- expects `contracts: [array of offer_ids]`
- sends back invalid ids with status 404
- `POST /offers/clear-hris-status`
- expects `contracts: [array of offer_ids]`
- `POST /offer/:offer_id/accept`
- returns status code with `message`

add admin accept and clear hris_status

---

app/controllers/offers_controller.rb
app/javascript/cp/appState.js
app/javascript/cp/components/controlPanel.js
app/javascript/cp/fetch.js

on top of #78 (may need to move 'accept' status check to front-end depending on @jmzaleski)

added ability to clear hr status, set offer as accepted from front-end

---

app/controllers/app_controller.rb
app/controllers/application_controller.rb
app/controllers/authorizer.rb
app/controllers/ddahs_controller.rb
app/controllers/export_controller.rb
app/controllers/offers_controller.rb
app/controllers/positions_controller.rb
app/controllers/sessions_controller.rb
app/controllers/templates_controller.rb
app/mailers/cp_mailer.rb
app/models/ddah.rb
app/views/app/ddah.html.erb
app/views/app/decision.html.erb
config/routes.rb
public/403.html
public/logout.html.erb

confirmed: 
implemented the following authorization:
New routes
Student access
instructor + admin access
admin access
--
--
--
--
--
--
Instructor access
--
--
--

[hotfix] create DDAH authorization

---

app/assets/stylesheets/cp.css
app/controllers/ddahs_controller.rb
app/controllers/templates_controller.rb
app/javascript/cp/appState.js
app/javascript/cp/components/adminControlPanel.js
app/javascript/cp/components/controlPanel.js
app/javascript/cp/components/ddahAppendix.js
app/javascript/cp/components/ddahControlPanel.js
app/javascript/cp/components/ddahForm.js
app/javascript/cp/components/instrControlPanel.js
app/javascript/cp/components/navbar.js
app/javascript/cp/fetch.js
app/javascript/cp/routeConfig.js
app/javascript/packs/cp.js
app/models/position.rb
app/services/templates/ddah_header.html.erb
db/schema.rb

[WIP] Ddah front end

---

app/controllers/ddahs_controller.rb
app/controllers/offers_controller.rb
app/javascript/cp/appState.js
app/javascript/cp/components/ddahControlPanel.js
app/javascript/cp/fetch.js
app/mailers/cp_mailer.rb
app/models/offer.rb
app/views/app/ddah.html.erb
app/views/cp_mailer/instructor_nag_email.html.erb
app/views/cp_mailer/instructor_nag_email.text.erb

- change nag-applicant-ddah to using `ddahs` instead of `offers`
- implement nag-instructor
- implement approve
- add checks for when offers has no ddahs
- add `instructor nag count` and `applicant nag count` to ddah control panel

[hotfix] fix ddah 

---

app/views/app/ddah.html.erb

- @reidka Please comment on whether this admonishment text is appropriate for the student view of the ddah

[hotfix] add admonishment text to DDAH student view

---

app/controllers/import_controller.rb
app/javascript/tapp/appState.js
app/javascript/tapp/components/importForm.js
app/javascript/tapp/fetch.js
app/services/instructor_importer.rb
config/routes.rb
db/seeds/instructor_data.json

- create instructor import route on backend
- create instructor importer on tapp summary page
- make semester option appear depending on if chass importing is selected
- add import instructor to tapp_access

[hotfix] Create Instructor Importer

---

app/controllers/ddah_updater.rb
app/services/csv_generator.rb
app/services/ddah_importer.rb

Michelle, Karen and Mathew in mathew's after over lunch.
Fails to re-import a freshly exported, unchanged .csv file.
(which karen needs to import spreadsheets created by instructors this season)

WIP: work at export/re-import run to completion

---

app/services/ddah_importer.rb

- sets the supervisor signature and date when ddah is imported
- update date when imported
- update ddah status to "Ready" when ddah status is:
- None/null
- Created
- @jmzaleski Do you think this make more sense than the previous status update?

[hotfix] fix requirements for updating ddah status after import

---

app/assets/stylesheets/cp.css
app/assets/stylesheets/tapp.css
app/javascript/cp/components/navbar.js
app/javascript/tapp/components/navbar.js

- created dropdown in Tapp/Cp for quick switch between apps

create quick switch for tapp-cp

---

app/controllers/assignments_controller.rb
app/views/tapp_mailer/assignment_email.html.erb
app/views/tapp_mailer/assignment_email.text.erb

added utorid column, sort by last name in assignment email

---

app/services/ddah_generator.rb

- fix layout breaking when course name is too long in ddah pdf header

[hotfix] fix ddah header

---

Gemfile
Gemfile.lock
app/controllers/export_controller.rb
app/javascript/cp/appState.js
app/javascript/cp/components/ddahControlPanel.js
app/javascript/cp/components/navbar.js
app/javascript/cp/fetch.js
config/routes.rb

- fixed issue with export ddah csv by position
- implement export of zipped ddah csv by session

Export zip of all ddah for session

---

app/javascript/tapp/appState.js

Sorted unassigned applications appState by checking preference, so its sorted in unassigned table by default.

Sort unassigned applications by preference

---

app/javascript/tapp/components/navbar.js

- as described in title
- fixes issue #112

display rounds in sorted order

---

app/controllers/assignments_controller.rb
app/controllers/ddah_updater.rb
app/controllers/ddahs_controller.rb
app/controllers/import_controller.rb
app/controllers/offers_controller.rb
app/javascript/cp/appState.js
app/javascript/cp/components/navbar.js
app/javascript/cp/fetch.js
app/javascript/fetchProc.js
app/javascript/tapp/appState.js
app/javascript/tapp/fetch.js
app/services/ddah_importer.rb
app/services/enrolment_updater.rb
app/services/offer_importer.rb
spec/controllers/offers_controller_spec.rb
spec/services/enrolment_updater_spec.rb

Clean up fetch.js and create fetchProc.js

---

app/javascript/tapp/fetch.js

[hotfix] fix chass export error due to typo

---

app/javascript/cp/fetch.js
app/javascript/fetchProc.js

- as described in title
- a bug Lisa discovered today
- needs to be merged soon to let her print out contracts

[Hotfix][Lisa requested] fix pdf viewing issue due to postData processing blob with resp.json()

---

app/javascript/cp/appState.js
app/javascript/cp/components/sessionsForm.js

- fixes issues as described in title

[Hotfix] fix pay refresh/update issue when switching sessions

---

app/views/app/decision.html.erb

- changed Lisa's listed office on `decision.html.erb`
- concerning the daily email, it seems like there's no errors that preventing the rake task from being fired
- perhaps, the cron job didn't fire(?)

[Hotfix] change Lisa's office to BA
